### PR TITLE
[Issue-55] fixes #55 and #56

### LINKED ISSUE #55: Need support for remote and virtual Repository creation
Need support for remote and virtual Repository creation

```
irb(main):142:0> repo = Repository.new(key: 'russ-repo2', rclass: 'remote', url: 'http://host:port/some-repo')
=> #<Repository blacked_out: nil, description: nil, checksum_policy_type: nil, excludes_pattern: nil, handle_releases: nil, handle_snapshots: nil, includes_pattern: nil, key: "russ-repo2", max_unique_snapshots: nil, notes: nil, property_sets: nil, repo_layout_ref: nil, rclass: "remote", snapshot_version_behavior: nil, suppress_pom_consistency_checks: nil, url: "http://host:port/some-repo">
irb(main):143:0> repo.save
NoMethodError: undefined method `url' for #<Artifactory::Resource::Repository:0x007fda8aaa7aa0>
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:300:in `block in to_hash'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:298:in `each'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:298:in `inject'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:298:in `to_hash'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:315:in `to_json'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/repository.rb:98:in `save'
    from (irb):143
    from /Users/rroy/.rbenv/versions/1.9.3-p547/bin/irb:12:in `<main>'
irb(main):144:0>
```

Or ... if you try to create a remote repo w/o the req'd url:

```
irb(main):145:0> repo = Repository.new(key: 'russ-repo2', rclass: 'remote')
=> #<Repository blacked_out: nil, description: nil, checksum_policy_type: nil, excludes_pattern: nil, handle_releases: nil, handle_snapshots: nil, includes_pattern: nil, key: "russ-repo2", max_unique_snapshots: nil, notes: nil, property_sets: nil, repo_layout_ref: nil, rclass: "remote", snapshot_version_behavior: nil, suppress_pom_consistency_checks: nil>
irb(main):146:0> repo.save
Artifactory::Error::HTTPError: The Artifactory server responded with an HTTP Error 400: `No URL defined for remote repository
'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/client.rb:374:in `error'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/client.rb:255:in `block in request'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/client.rb:245:in `request'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/client.rb:131:in `put'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/repository.rb:98:in `save'
    from (irb):146
    from /Users/rroy/.rbenv/versions/1.9.3-p547/bin/irb:12:in `<main>'
irb(main):147:0>
```

### PR DESCRIPTION
**Pull request by antoniobeyah**
@schisamo this pr addresses issues #56 and #55

### CODE REVIEW

**Comment by schisamo** [comment]
Thank you for the contribution @antoniobeyah. Quick style question for you. I noticed you made the shared "base" logic a module that is mixed into the classes for the two repo types. Is there anything barring this being structured as traditional parent/child relationship? We could then structure things with a module (`resources/repository.rb`) that autoloads the main implementations which are grouped in a subdirectory (`resources/repositories/base.rb`, `resources/repositories/virtual.rb`, `resources/repositories/remote.rb` etc.).

Our Omnibus project's packagers has a good example:
https://github.com/chef/omnibus/blob/master/lib/omnibus/packager.rb
https://github.com/chef/omnibus/blob/master/lib/omnibus/packagers/base.rb
https://github.com/chef/omnibus/blob/master/lib/omnibus/packagers/deb.rb
https://github.com/chef/omnibus/blob/master/lib/omnibus/packagers/msi.rb

**Comment by antoniobeyah** [comment]
The only thing preventing me from doing that was that they are currently inheriting from Resource::Base which provides the functionality for the .attribute behavior.  I suppose I could have created a new base the inherited from Resource::Base and changed them all to point to that.  I wasn't too familiar with the why's behind the structure so I tried to fit in as much as possible. 

I also updated the existing Repository class to mixin the new module but I did not rename it to be inline with the others. (LocalRepository, VirtualRepository, RemoteRepository) are the classes that should exist but I left Repository instead of renaming it to LocalRepository to maintain some backwards compatibility.  I am curious on your ideas on removing the Repository class altogether.

I can try to make it match what you are suggesting, I would also make the change to move the Repository class to become LocalRepository.  Given the implications will that be an acceptable change?

**Comment by schisamo** [comment]
@sethvargo Thoughts on the best way to structure this change? Since you architected the original code I figure you'll have opinions.

**Comment by sethvargo** [comment]
Code changes look good. I agree that the naming is a bit weird. If "repository" is too generic, we should move it into a folder and rename.

**Comment by schisamo** [comment]
Closing as this was fixed as part of https://github.com/chef/artifactory-client/pull/69.

**Pull request closed without merging**
