### PR TITLE
[issue-56] added support for the new artifactory 4.x package type

### PR DESCRIPTION
**Pull request by antoniobeyah**

### CODE REVIEW

**Comment by antoniobeyah** [comment]
Not sure if this is backwards compatible with artifactory 3.x as i don't have an artifactory 3.x installation to test against.  From my testing though, Artifactory seems to ignore additional attributes that it does not know about.

**Comment by antoniobeyah** [comment]
#56

**Comment by antoniobeyah** [comment]
Also, I set the default repository type to 'maven' instead of 'generic' as it seemed to make more sense and inline with the current code.  I wasn't a big fan of all of the duplication of the json objects but I didn't want to get too crazy refactoring for this minor change.

**Comment by yzl** [comment]
Rebased and merged as part of #64.

**Pull request closed without merging**
