### PR TITLE
Support for Build endpoints

### PR DESCRIPTION
**Pull request by schisamo**
See the following for more details on what 'builds' mean in the Artifactory world:
https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-BUILDS
https://www.jfrog.com/confluence/display/RTF/Build+Integration
https://github.com/JFrogDev/build-info

/cc @chef/ociv @sethvargo

### CODE REVIEW

**Comment by sethvargo** [comment]
This seems reasonable to me. Is there a way to check if this is supported in the users' Artifactory version? I worry about people thinking this will work on older versions of Artifactory that don't support these new "build" schema.

**Comment by schisamo** [comment]
@sethvargo From what I can gather that build schema has never changed. :)

**Comment by sethvargo** [comment]
Oh oh. Nvm - I thought this was related to the new things announced at SwampUp

:+1:

**Comment by yzl** [comment]
lgtm

**Pull request merged**
